# Build stage
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --silent
COPY . .
ARG VITE_APP_NAME=Armada
ARG VITE_KLIPY_API_KEY=
ARG VITE_APP_RELAYS=wss://relay.ditto.pub,wss://relay.dreamith.to
ARG VITE_SEARCH_RELAYS=wss://relay.ditto.pub,wss://relay.dreamith.to
ARG VITE_APP_BLOSSOM_SERVERS=https://blossom.ditto.pub/,https://blossom.dreamith.to/,https://blossom.primal.net/
ARG VITE_DEFAULT_NOISE_SUPPRESSION=true
ARG VITE_DEFAULT_ECHO_CANCELLATION=true
ARG VITE_DEFAULT_AUTO_GAIN_CONTROL=true
ARG VITE_SANDBOX_DOMAIN=iframe.diy
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_KLIPY_API_KEY=$VITE_KLIPY_API_KEY
ENV VITE_APP_RELAYS=$VITE_APP_RELAYS
ENV VITE_SEARCH_RELAYS=$VITE_SEARCH_RELAYS
ENV VITE_APP_BLOSSOM_SERVERS=$VITE_APP_BLOSSOM_SERVERS
ENV VITE_DEFAULT_NOISE_SUPPRESSION=$VITE_DEFAULT_NOISE_SUPPRESSION
ENV VITE_DEFAULT_ECHO_CANCELLATION=$VITE_DEFAULT_ECHO_CANCELLATION
ENV VITE_DEFAULT_AUTO_GAIN_CONTROL=$VITE_DEFAULT_AUTO_GAIN_CONTROL
ENV VITE_SANDBOX_DOMAIN=$VITE_SANDBOX_DOMAIN
RUN npm run build

# Runtime stage
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
