import { Bell, ChevronLeft, CircleDot, GitPullRequest, MessageCircle, MoreVertical, Search, Settings2, Users, X } from "lucide-react";
import { useState } from "react";

import { MessageRow } from "@/components/chat/MessageRow";
import { ChannelSidebarView } from "@/components/layout/ChannelSidebarView";
import { ServerRail } from "@/components/layout/ServerRail";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type WorkItem = { type: "Pull request" | "Issue"; number: string; title: string; repository: string; replies: number };
type Actor = { name: string; initials: string; color: string; time: string; external?: boolean };
type WorkItemComment = { actor: Actor; body: string; earlierComments?: number; laterComments?: number };

const notificationControls: WorkItem = { type: "Pull request", number: "PR-42", title: "Add per-channel notification controls", repository: "armada", replies: 5 };
const voiceReconnect: WorkItem = { type: "Issue", number: "ISSUE-91", title: "Voice reconnect loses the selected input device", repository: "armada-android", replies: 3 };
const notificationControlComments: WorkItemComment[] = [
  { actor: { name: "Dan Conway", initials: "DC", color: "#0284c7", time: "8m" }, body: "Could we make “Mentions only” the default for newly joined channels? That avoids a surprise flood after accepting an invite.", laterComments: 3 },
  { actor: { name: "Maya Chen", initials: "MC", color: "#8b5cf6", time: "7m" }, body: "Yes — I added that to the latest commit and migration path." },
  { actor: { name: "Priya Shah", initials: "PS", color: "#db2777", time: "5m", external: true }, body: "The empty-state copy should explain that channel defaults can still be changed later.", earlierComments: 2, laterComments: 2 },
  { actor: { name: "Dan Conway", initials: "DC", color: "#0284c7", time: "3m" }, body: "Good call. The migration behavior and empty state both look ready after that." },
  { actor: { name: "Maya Chen", initials: "MC", color: "#8b5cf6", time: "1m" }, body: "Updated both. I’ll mark this ready for review after the screenshot test finishes." },
];
const voiceReconnectComments: WorkItemComment[] = [
  { actor: { name: "Noah Williams", initials: "NW", color: "#059669", time: "4m" }, body: "I can reproduce this after switching from Bluetooth to the phone microphone during a reconnect." },
  { actor: { name: "Dan Conway", initials: "DC", color: "#0284c7", time: "2m" }, body: "I found the device ID being cleared before the reconnect state is restored. I’ll send a fix shortly.", earlierComments: 1, laterComments: 1 },
  { actor: { name: "Noah Williams", initials: "NW", color: "#059669", time: "now" }, body: "Thanks — I’ll verify the Android build once it lands." },
];

function ChannelRow({ name, active, unread }: { name: string; active?: boolean; unread?: boolean }) {
  return <button type="button" className={cn("flex w-full items-center gap-2 rounded-md py-1.5 pl-4 pr-2 text-left text-sm transition-colors", active ? "bg-secondary font-medium text-foreground" : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground")}><span className="text-base leading-none">#</span><span className="min-w-0 flex-1 truncate">{name}</span>{unread && <span className="size-2 rounded-full bg-primary" />}</button>;
}

function ItemIcon({ item }: { item: WorkItem }) {
  const Icon = item.type === "Issue" ? CircleDot : GitPullRequest;
  return <Icon className={cn("size-4 shrink-0", item.type === "Issue" ? "text-emerald-500" : "text-violet-500")} />;
}

function ContextHeader({ item, onOpen }: { item: WorkItem; onOpen: () => void }) {
  return <button type="button" onClick={onOpen} className="flex w-full items-center gap-2 rounded-t-lg border border-b-0 border-border bg-secondary/45 px-3 py-2 text-left transition-colors hover:bg-secondary"><ItemIcon item={item} /><span className="min-w-0 flex-1 truncate text-xs font-medium">{item.title}</span><span className="shrink-0 font-mono text-[10px] text-muted-foreground">{item.repository} · {item.number}</span></button>;
}

function WorkItemActivity({ item, actor, onOpen }: { item: WorkItem; actor: Actor; onOpen: () => void }) {
  const action = item.type === "Issue" ? "opened an issue" : "opened a pull request";
  return <article className="mx-auto my-4 flex max-w-2xl gap-2.5"><Avatar className="mt-1 size-8 shrink-0"><AvatarFallback style={{ backgroundColor: actor.color }} className="text-[10px] font-semibold text-white">{actor.initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="text-sm"><span className="font-semibold">{actor.name}</span><span className="text-muted-foreground"> {action} in {item.repository} · {actor.time}</span></p><button type="button" onClick={onOpen} className="mt-2 block w-full rounded-lg border border-border bg-card p-3 text-left shadow-sm transition-colors hover:bg-secondary/30"><div className="flex items-center gap-2"><ItemIcon item={item} /><span className="text-xs text-muted-foreground">{item.type}</span><span className="font-mono text-[10px] text-muted-foreground">{item.number}</span></div><p className="mt-2 text-sm font-semibold">{item.title}</p><p className="mt-1 text-sm leading-5 text-muted-foreground">Follow the work item here without leaving the channel.</p><span className="mt-3 flex items-center gap-1.5 text-xs text-primary"><MessageCircle className="size-3.5" />{item.replies} comments · Open conversation</span></button>{item === voiceReconnect && <CommentActivity item={item} comments={voiceReconnectComments} onOpen={onOpen} />}</div></article>;
}

function CommentActivity({ item, comments, onOpen }: { item: WorkItem; comments: WorkItemComment[]; onOpen: () => void }) {
  const { earlierComments = 0, laterComments = 0 } = comments[0] ?? {};

  return <article className={cn("mx-auto my-4 max-w-2xl", item === voiceReconnect && "-ml-10 max-w-none")}><ContextHeader item={item} onOpen={onOpen} /><div className="rounded-b-lg border border-border bg-card px-3 py-3 shadow-sm">{earlierComments > 0 && <button type="button" onClick={onOpen} className="mb-3 text-[10px] text-muted-foreground/70 hover:text-muted-foreground">↑ Earlier comments</button>}<div className="space-y-3">{comments.map(({ actor, body }) => <div key={`${actor.name}-${actor.time}`} className="flex gap-2.5"><Avatar className="size-8 shrink-0"><AvatarFallback style={{ backgroundColor: actor.color }} className="text-[10px] font-semibold text-white">{actor.initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex items-baseline gap-2"><span className="text-sm font-semibold">{actor.name}</span>{actor.external && <span className="rounded border border-border px-1 py-px text-[9px] font-medium uppercase tracking-wide text-muted-foreground">Guest</span>}<span className="text-xs text-muted-foreground">commented · {actor.time}</span></div><p className="mt-1 text-sm leading-5 text-foreground">{body}</p></div></div>)}</div>{laterComments > 0 && <button type="button" onClick={onOpen} className="mt-3 text-[10px] text-muted-foreground/70 hover:text-muted-foreground">↓ Later comments</button>}<button type="button" onClick={onOpen} className="mt-3 flex items-center gap-1.5 text-xs text-primary hover:underline"><MessageCircle className="size-3.5" />View all {item.replies} comments in context</button></div></article>;
}

export function GitMockupThreePage() {
  const [contextItem, setContextItem] = useState<WorkItem | null>(notificationControls);
  const now = Date.now() / 1000;

  return <div className="flex h-full min-h-0 bg-background"><ServerRail /><ChannelSidebarView title="Armada contributors" subtitle="Community" className="hidden sidebar:flex" addChannelDisabled><button type="button" className="flex w-full items-center gap-2 rounded-md py-1.5 pl-4 pr-2 text-left text-sm text-muted-foreground hover:bg-secondary/60"><Bell className="size-4" />Mentions<span className="ml-auto rounded-full bg-primary px-1.5 text-[10px] text-primary-foreground">2</span></button><ChannelRow name="general" /><ChannelRow name="design" /><ChannelRow name="engineering" active unread /><ChannelRow name="release-work" /></ChannelSidebarView>
    <main className="flex min-w-0 flex-1 flex-col safe-area-top"><header className="relative mx-2 mt-3 flex h-12 shrink-0 items-center gap-1.5 bg-chrome px-2 clip-corner-lg sidebar:px-3"><Button variant="ghost" size="icon" className="size-9 shrink-0 sidebar:hidden" aria-label="Back to channels"><ChevronLeft className="size-5" /></Button><span className="text-xl text-muted-foreground">#</span><div className="min-w-0 flex-1"><h1 className="truncate font-semibold leading-tight">engineering</h1><p className="truncate text-xs text-muted-foreground">Build notes, reviews, and implementation discussion</p></div><Button variant="ghost" size="icon" className="size-8 text-muted-foreground" aria-label="Search channel"><Search className="size-4" /></Button><Button variant="ghost" size="icon" className="size-8 text-muted-foreground" aria-label="Community members"><Users className="size-4" /></Button><Button variant="ghost" size="icon" className="size-8 text-muted-foreground" aria-label="Channel settings"><Settings2 className="size-4" /></Button><Button variant="ghost" size="icon" className="size-8 text-muted-foreground" aria-label="More channel options"><MoreVertical className="size-4" /></Button></header>
      <div className="flex min-h-0 flex-1"><section className="min-w-0 flex-1 overflow-y-auto pb-6 pt-5"><div className="mx-auto max-w-3xl"><div className="mb-5 border-b border-border px-4 pb-5"><h2 className="text-xl font-bold">Welcome to #engineering</h2><p className="mt-2 text-sm leading-5 text-muted-foreground">Discuss implementation with the community. Connected repository activity can appear naturally in this conversation.</p></div><div className="px-2 sidebar:px-4"><div className="mb-4 flex items-center gap-3 text-[11px] font-medium text-muted-foreground"><span className="h-px flex-1 bg-border" />TODAY<span className="h-px flex-1 bg-border" /></div><MessageRow pubkey="mock-ak" identityOverride={{ name: "Ari Kline", suffix: "dev", color: "#d97706" }} createdAt={now - 55 * 60}><p className="text-sm leading-5">I’m testing the new notification settings now. The channel-level defaults look good on desktop.</p></MessageRow><WorkItemActivity item={notificationControls} actor={{ name: "Maya Chen", initials: "MC", color: "#8b5cf6", time: "12m" }} onOpen={() => setContextItem(notificationControls)} /><CommentActivity item={notificationControls} comments={notificationControlComments.slice(0, 2)} onOpen={() => setContextItem(notificationControls)} /><MessageRow pubkey="mock-ak" identityOverride={{ name: "Ari Kline", suffix: "dev", color: "#d97706" }} createdAt={now - 6 * 60}><p className="text-sm leading-5">I’m updating the desktop screenshots now. The new defaults read clearly in the channel picker.</p></MessageRow><CommentActivity item={notificationControls} comments={notificationControlComments.slice(2, 3)} onOpen={() => setContextItem(notificationControls)} /><MessageRow pubkey="mock-mc" identityOverride={{ name: "Maya Chen", suffix: "dev", color: "#8b5cf6" }} createdAt={now - 2 * 60}><p className="text-sm leading-5">I’ll post the release checklist here before lunch.</p></MessageRow><WorkItemActivity item={voiceReconnect} actor={{ name: "Noah Williams", initials: "NW", color: "#059669", time: "6m" }} onOpen={() => setContextItem(voiceReconnect)} /></div></div></section>
        <aside className={cn("hidden shrink-0 overflow-hidden border-l border-border bg-chrome sidebar:flex sidebar:transition-[width] sidebar:duration-200", contextItem ? "sidebar:w-[21rem]" : "sidebar:w-0")}>{contextItem && <div className="flex w-[21rem] min-w-[21rem] flex-col"><div className="flex h-12 items-center border-b border-border px-3"><p className="text-sm font-semibold">Conversation</p><Button variant="ghost" size="icon" onClick={() => setContextItem(null)} className="ml-auto size-8" aria-label="Close conversation"><X className="size-4" /></Button></div><div className="min-h-0 flex-1 overflow-y-auto p-3"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground"><ItemIcon item={contextItem} />{contextItem.type} · {contextItem.number}</div><h3 className="mt-2 text-sm font-semibold">{contextItem.title}</h3><p className="mt-1 text-xs text-muted-foreground">{contextItem.repository} · Open</p><div className="my-4 border-t border-border" /><p className="text-xs text-muted-foreground">This is the work item’s durable discussion. Its card in #engineering is a contextual reference, not a chat thread.</p><div className="mt-4 space-y-4"><div className="rounded-lg border border-border bg-background p-3"><p className="text-xs font-semibold">Dan Conway <span className="font-normal text-muted-foreground">· 8m</span></p><p className="mt-1 text-sm leading-5">Could we make “Mentions only” the default for newly joined channels?</p></div><div className="rounded-lg border border-border bg-background p-3"><p className="text-xs font-semibold">Maya Chen <span className="font-normal text-muted-foreground">· 4m</span></p><p className="mt-1 text-sm leading-5">Yes — I added that to the latest commit and migration path.</p></div></div></div><div className="border-t border-border p-3"><button type="button" className="w-full rounded-md border border-border bg-background px-3 py-2 text-left text-sm text-muted-foreground">Add a comment…</button></div></div>}</aside></div></main></div>;
}
