/**
 * CORD-02 §8 fragmented Community List — the wire layer.
 *
 * Ports the reference implementation's test suite (Vector `list_frag.rs`)
 * one-for-one, then adds the cross-client teeth: a GOLDEN byte-parity fixture
 * generated by serde_json over the reference structs (BTreeMap extras, flatten
 * appended after declared fields, sorted keys at every depth), which
 * `serializeFragList` must reproduce byte-for-byte. Two devices holding
 * identical state must serialize identical bytes, or §8's canonical-bytes
 * tie-break flaps between them.
 */

import { Buffer } from "node:buffer";

import { describe, expect, it } from "vitest";

import type { CommunityList, CommunityListEntry, JoinMaterial } from "./communityList";
import { isLive } from "./communityList";
import {
  PACK_TARGET_BYTES,
  defragment,
  fragment,
  nip44PaddedLen,
  parseFragList,
  projectedEventBytes,
  serializeFragList,
} from "./listFrag";

const hex32 = (byte: number) => byte.toString(16).padStart(2, "0").repeat(32);
/** Independent base64url oracle — not the implementation under test. */
const b64of = (hex: string) => Buffer.from(hex, "hex").toString("base64url");

function jm(name: string): JoinMaterial {
  return {
    community_id: hex32(0x11),
    owner: hex32(0x22),
    owner_salt: hex32(0x33),
    community_root: hex32(0x44),
    root_epoch: 3,
    control_pk: hex32(0x55),
    channels: [],
    relays: ["wss://relay.example.com"],
    name,
  };
}

function entry(seed: JoinMaterial, current: JoinMaterial): CommunityListEntry {
  return { community_id: hex32(0x11), seed, current, added_at: 1_719_800_000_000 };
}

function listOf(entries: CommunityListEntry[]): CommunityList {
  return { entries, tombstones: [] };
}

describe("encoding", () => {
  it("32-byte values become 43-char unpadded base64url", () => {
    const f = fragment(listOf([entry(jm("x"), jm("x"))]));
    const m = f[0].entries[0].current;
    expect(m.owner).toHaveLength(43);
    expect(f[0].entries[0].community_id).toHaveLength(43);
    expect(m.owner).not.toContain("="); // padding would give one value two spellings
    // Against an independent encoder, not our own inverse.
    expect(f[0].entries[0].community_id).toBe(b64of(hex32(0x11)));
    expect(m.owner).toBe(b64of(hex32(0x22)));
  });

  it("seed is omitted when it equals current", () => {
    const f = fragment(listOf([entry(jm("x"), jm("x"))]));
    expect(f[0].entries[0].seed).toBeUndefined();
    // ...and kept when it genuinely differs.
    const older = { ...jm("x"), root_epoch: 1 };
    const g = fragment(listOf([entry(older, jm("x"))]));
    expect(g[0].entries[0].seed).toBeDefined();
  });

  it("a tombstoned entry is dropped but its tombstone is not", () => {
    const l = listOf([entry(jm("x"), jm("x"))]);
    l.tombstones.push({ community_id: hex32(0x11), removed_at: l.entries[0].added_at + 1 });
    const f = fragment(l);
    expect(f[0].entries).toHaveLength(0); // the retired entry's snapshots and keys leave the wire
    expect(f[0].tombstones).toHaveLength(1); // the removal itself is permanent
    expect(isLive(defragment(f), hex32(0x11))).toBe(false);

    // A re-join out-ranks the tombstone, so its entry rides again.
    l.entries[0].added_at = l.tombstones[0].removed_at + 1;
    const g = fragment(l);
    expect(g[0].entries).toHaveLength(1);
    expect(isLive(defragment(g), hex32(0x11))).toBe(true);
  });

  it("embedded snapshots carry no community_id", () => {
    const f = fragment(listOf([entry(jm("x"), jm("x"))]));
    expect(serializeFragList(f[0])).not.toContain(`"community_id":"${hex32(0x11)}"`);
    const parsed = JSON.parse(serializeFragList(f[0]));
    expect(parsed.entries[0].current.community_id).toBeUndefined(); // the entry already keys it
  });

  it("unknown fields survive at every level", () => {
    const m = jm("x");
    m.held_roots = [{ epoch: 1, key: "kk" }];
    m.channels.push({
      id: hex32(0x66),
      key: hex32(0x77),
      epoch: 2,
      name: "staff",
      priors: [{ key: "pp", epoch: 1 }],
    });
    const f = fragment(listOf([entry(structuredClone(m), m)]));
    const cur = f[0].entries[0].current;
    expect(cur.extra.held_roots).toEqual([{ epoch: 1, key: "kk" }]);
    expect(cur.channels[0].extra.priors).toEqual([{ key: "pp", epoch: 1 }]); // priors must not be dropped
  });

  it("a list survives fragment then defragment unchanged", () => {
    const refoundedSeed = { ...jm("Refounded"), root_epoch: 1 };
    const staff = jm("Staffed");
    staff.control_root = hex32(0x99);
    staff.channels = [
      { id: hex32(0x66), key: hex32(0x77), epoch: 2, name: "staff", priors: [{ key: "ab".repeat(32), epoch: 1 }] },
    ];
    const before: CommunityList = {
      entries: [
        entry(jm("Plain"), jm("Plain")), // seed == current
        entry(refoundedSeed, jm("Refounded")), // seed differs
        entry(structuredClone(staff), staff), // control_root + priors
      ],
      tombstones: [{ community_id: hex32(0xaa), removed_at: 1_722_400_000_000 }],
    };
    const after = defragment(fragment(before));
    expect(after).toEqual(before); // fragmenting and defragmenting must be lossless
  });

  it("unknown encodings round-trip untouched", () => {
    // An unknown field holding 32 bytes of hex must come back as it went in:
    // a client cannot re-encode what it cannot interpret.
    const m = jm("x");
    m.refounder = "cd".repeat(32);
    const before = listOf([entry(structuredClone(m), m)]);
    const after = defragment(fragment(before));
    expect(after.entries[0].current.refounder).toBe("cd".repeat(32));
    expect(after).toEqual(before);
  });

  it("an absent seed reads back as equal to current", () => {
    const f = fragment(listOf([entry(jm("x"), jm("x"))]));
    const wire = serializeFragList(f[0]);
    const back = defragment([parseFragList(wire)]);
    expect(back.entries[0].seed).toEqual(back.entries[0].current);
  });
});

describe("fragmentation", () => {
  it("a multi-fragment list defragments whole", () => {
    const entries: CommunityListEntry[] = [];
    for (let i = 0; i < 400; i++) {
      const m = { ...jm(`community ${i}`), owner: hex32(i % 251) };
      const e = entry(structuredClone(m), m);
      e.community_id = i.toString(16).padStart(64, "0");
      entries.push(e);
    }
    const before = listOf(entries);
    const frags = fragment(before);
    expect(frags.length).toBeGreaterThan(1); // 400 memberships must span fragments
    expect(defragment(frags).entries).toHaveLength(before.entries.length); // no entry lost across the split
  });

  it("nip44 padding matches the spec", () => {
    expect(nip44PaddedLen(1)).toBe(32);
    expect(nip44PaddedLen(32)).toBe(32);
    expect(nip44PaddedLen(33)).toBe(64);
    expect(nip44PaddedLen(100)).toBe(128);
  });

  it("fragments split before the event ceiling", () => {
    const entries = Array.from({ length: 400 }, () =>
      entry(jm("a community with a name"), jm("a community with a name")),
    );
    const f = fragment(listOf(entries));
    expect(f.length).toBeGreaterThan(1); // 400 memberships must not fit one event
    const utf8 = new TextEncoder();
    for (const frag of f) {
      // Packed to the TARGET, not the ceiling — an event at 65,536 exactly
      // is a coin-flip between one relay's `>` and another's `>=`.
      expect(projectedEventBytes(utf8.encode(serializeFragList(frag)).length)).toBeLessThanOrEqual(PACK_TARGET_BYTES);
      expect(frag.frags).toBe(f.length); // every fragment declares the total
    }
  });

  it("a rename never forks seed from current", () => {
    // Same keys and epoch, renamed community + channel + moved relays: the
    // stale labels must not re-materialize the duplicate snapshot.
    const old = { ...jm("Old Name"), relays: ["wss://old.example.com"] };
    old.channels = [{ id: hex32(0x66), key: hex32(0x77), epoch: 2, name: "old-general" }];
    const fresh = jm("New Name");
    fresh.channels = [{ id: hex32(0x66), key: hex32(0x77), epoch: 2, name: "general" }];
    const f = fragment(listOf([entry(old, fresh)]));
    expect(f[0].entries[0].seed).toBeUndefined(); // cosmetic drift is not a difference

    // A real divergence (an older epoch) keeps seed — carrying current's cosmetics.
    const refounded = { ...jm("Old Name"), root_epoch: 1 };
    const g = fragment(listOf([entry(refounded, jm("New Name"))]));
    const seed = g[0].entries[0].seed;
    expect(seed).toBeDefined(); // an older epoch is a real difference
    expect(seed!.name).toBe("New Name"); // seed's cosmetic fields are current's
  });

  it("an empty list still serializes one publishable fragment", () => {
    const f = fragment({ entries: [], tombstones: [] });
    expect(f).toHaveLength(1);
    expect(serializeFragList(f[0])).toBe('{"frags":1}');
  });

  it("fragment-level unknowns ride on fragment 0 and union lowest-index-first", () => {
    const l: CommunityList = { entries: [], tombstones: [], vendor_note: "keep me" };
    const f = fragment(l);
    expect(f[0].extra.vendor_note).toBe("keep me");
    // On read, the lowest index wins a duplicated key.
    const a = parseFragList('{"frags":2,"vendor_note":"low"}');
    const b = parseFragList('{"frags":2,"vendor_note":"high"}');
    expect(defragment([a, b]).vendor_note).toBe("low");
  });
});

describe("parsing strictness (mirrors the reference deserializer)", () => {
  it("a fragment without frags is unreadable", () => {
    expect(() => parseFragList('{"entries":[]}')).toThrow();
  });

  it("a malformed entry rejects the whole fragment", () => {
    expect(() => parseFragList('{"frags":1,"entries":[{"community_id":"aa"}]}')).toThrow();
    expect(() =>
      parseFragList(
        '{"frags":1,"entries":[{"community_id":"aa","current":{"owner":"o","owner_salt":"s","community_root":"r","root_epoch":1,"name":"n"},"added_at":1.5}]}',
      ),
    ).toThrow(); // added_at is a u64, not a float
  });

  it("null where a defaulted array belongs is an error, absence is not", () => {
    const ok = parseFragList(
      '{"frags":1,"entries":[{"community_id":"aa","current":{"owner":"o","owner_salt":"s","community_root":"r","root_epoch":1,"name":"n"},"added_at":5}]}',
    );
    expect(ok.entries[0].current.channels).toEqual([]);
    expect(ok.entries[0].current.relays).toEqual([]);
    expect(() =>
      parseFragList(
        '{"frags":1,"entries":[{"community_id":"aa","current":{"owner":"o","owner_salt":"s","community_root":"r","root_epoch":1,"channels":null,"name":"n"},"added_at":5}]}',
      ),
    ).toThrow();
  });

  it("a keyless channel parses and is never written back with a key", () => {
    // GOLDEN, cross-client: a channel the account holds NO key for omits `key`
    // entirely. One such channel must never reject the whole vault document.
    const wire =
      '{"frags":1,"entries":[{"community_id":"aa","current":{"owner":"o","owner_salt":"s","community_root":"r","root_epoch":1,"channels":[{"id":"c1","key":"kk","epoch":2,"name":"keyed"},{"id":"c2","epoch":0,"name":"not-granted"}],"name":"n"},"added_at":5}]}';
    const parsed = parseFragList(wire);
    const chans = parsed.entries[0].current.channels;
    expect(chans).toHaveLength(2);
    expect(chans[0].key).toBe("kk");
    expect(chans[1].key).toBeUndefined();
    expect(serializeFragList(parsed)).toBe(wire); // absent stays absent, byte-for-byte
  });
});

describe("byte parity with the reference implementation", () => {
  // Generated by serde_json 1.0.149 over the reference structs (FragList et
  // al., BTreeMap-backed extras): parse the shuffled wire document below and
  // re-serialize. Declared fields in order, flattened extras appended after
  // them sorted lexicographically (integer-like keys NOT hoisted), unknown
  // values re-emitted with sorted keys at every depth, control characters
  // escaped \u0007-style, unicode raw.
  const SHUFFLED_WIRE = String.raw`{
      "frags": 1,
      "zzz_list_extra": {"b":1,"a":[{"y":2,"x":1}]},
      "0": "integer-like key",
      "entries": [{
        "community_id": "PxpVK3nQ7sB1yTfWm4dLxZ0aRcE9uHgKjNvOpQrStUv",
        "current": {
          "owner": "nC7hQ2eRtYuIoPaSdFgHjKlZxCvBnM1qW3eR5tY7uI9",
          "owner_salt": "qhEwR9tYuIoPaSdFgHjKlZxCvBnM1qW3eR5tY7uI0oP",
          "community_root": "d70Xa1QwErTyUiOpAsDfGhJkLzXcVbNm2Qw4Er6Ty8U",
          "root_epoch": 3,
          "channels": [
            {"id": "Ch1dQwErTyUiOpAsDfGhJkLzXcVbNm2Qw4Er6Ty8U0i", "epoch": 2, "name": "staff \" \\ ü🎉 \u0007",
             "priors": [{"key":"abab","epoch":1}], "aaa_first": true}
          ],
          "relays": ["wss://relay.example.com"],
          "name": "Example",
          "held_roots": [{"epoch":1,"key":"cdcd"}],
          "refounder": "ffff",
          "123": 7,
          "aaa_sorts_before_owner": true
        },
        "added_at": 1719800000000,
        "excluded_at_epoch": 4,
        "channel_cuts": [{"id":"abcd","epoch":2}],
        "invite_ref": "naddr#frag"
      }]
    }`;
  const SERDE_GOLDEN = String.raw`{"frags":1,"entries":[{"community_id":"PxpVK3nQ7sB1yTfWm4dLxZ0aRcE9uHgKjNvOpQrStUv","current":{"owner":"nC7hQ2eRtYuIoPaSdFgHjKlZxCvBnM1qW3eR5tY7uI9","owner_salt":"qhEwR9tYuIoPaSdFgHjKlZxCvBnM1qW3eR5tY7uI0oP","community_root":"d70Xa1QwErTyUiOpAsDfGhJkLzXcVbNm2Qw4Er6Ty8U","root_epoch":3,"channels":[{"id":"Ch1dQwErTyUiOpAsDfGhJkLzXcVbNm2Qw4Er6Ty8U0i","epoch":2,"name":"staff \" \\ ü🎉 \u0007","aaa_first":true,"priors":[{"epoch":1,"key":"abab"}]}],"relays":["wss://relay.example.com"],"name":"Example","123":7,"aaa_sorts_before_owner":true,"held_roots":[{"epoch":1,"key":"cdcd"}],"refounder":"ffff"},"added_at":1719800000000,"channel_cuts":[{"epoch":2,"id":"abcd"}],"excluded_at_epoch":4,"invite_ref":"naddr#frag"}],"0":"integer-like key","zzz_list_extra":{"a":[{"x":1,"y":2}],"b":1}}`;

  it("re-serializes a foreign document to the reference's exact bytes", () => {
    expect(serializeFragList(parseFragList(SHUFFLED_WIRE))).toBe(SERDE_GOLDEN);
  });

  it("the golden itself is a fixed point", () => {
    expect(serializeFragList(parseFragList(SERDE_GOLDEN))).toBe(SERDE_GOLDEN);
  });

  it("fragmenting identical state twice yields identical bytes", () => {
    const m = jm("Deterministic");
    m.held_roots = [{ epoch: 1, key: "aa".repeat(32) }];
    const a = fragment(listOf([entry(structuredClone(m), structuredClone(m))]));
    const b = fragment(listOf([entry(structuredClone(m), structuredClone(m))]));
    expect(serializeFragList(a[0])).toBe(serializeFragList(b[0]));
  });
});
